project_id = "phujiyshbhiujzcvrrkf"

[functions.translate]
verify_jwt = false

[functions.tryon-leffa]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.sync-stripe-products]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
